---
title: "532_shiny"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Milestone 2

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
```

```{r, message=FALSE}
wine <- read_csv("winemag-data-130k-v2.csv")
wine <- subset(wine, select = -X1 )
names(wine)[4] <- "quality"
```

```{r}
#unique(wine$variety)
```

```{r}
# join the two tables here to create a map 
world <- map_data("world")
highlighted <- subset(world, region == "Canada")

#names(wine)[1] <- "region"




#test <- left_join(world,wine)

w_count <- wine %>%
  group_by(country) %>% 
  mutate(count = n()) %>% # count the # of entries in each country
  select(country, count)

w_count <- unique(w_count)
names(w_count)[1] <- "region"

test <- left_join(world,w_count)
```
```{r}
highlighted <- world %>% 
  filter(region == "Canada")

max(wine$quality)
```

```{r}
(map <- ggplot(test) +
  geom_polygon(aes(x=long, y = lat, group = group, fill = count)) + 
  guides(fill = FALSE) + 
  theme_minimal() +
  scale_fill_gradient(low = "misty rose",high = "violetred4", name= "Numbers of \nEntries") + 
  xlab("Longitude") + 
  ylab("Latitude"))


map +
  geom_polygon(data = highlighted, aes(x = long, y = lat,group = group), fill = NA, colour = "black")
```

```{r}
canada <- wine %>% 
  filter(country == "Canada")

ggplot(canada, aes(price)) +
  geom_histogram(binwidth = 5)
```

```{r}
ggplot(highlighted) +
  geom_polygon(aes(x=long, y = lat, fill = count)) + 
  #guides(fill = FALSE) + 
  theme_minimal() +
  scale_fill_gradient(low = "misty rose",high = "violetred4", name= "Numbers of \nEntries") + 
  xlab("Longitude") + 
  ylab("Latitude")
```


```{r}
list <- sort(unique(wine$country))

list2 <- sort(unique(wine$variety))
```

